---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: livingdocs/varnish
    tags: [6.4.0-r0, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: livingdocs/varnish
    tags: [6.4.0-r0, latest]
  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: 996086d03a38901ba8898e2eba716db36887df3029033dc89cc02b780e1640c8

...
