---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r2, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r2, latest]

  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: 6a2315be41766e147ad06c88d025af425ea522b0365c26d0f508912ce39baba8

...
