language: generic

services:
  - docker

env:
  - VERSION=5.1.3-r0 NAME=varnish513 TAGS="livingdocs/bluewin-varnish:5.1.3-r0 livingdocs/bluewin-varnish:latest"

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build --build-arg VERSION=$VERSION -t $NAME .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      for tag in $TAGS; do
        docker tag $NAME $tag;
        echo "push the image $tag";
        docker push $tag 1>/dev/null;
        echo "successfully pushed the image $tag";
      done
    fi
