version: 2.1
orbs:
  node: circleci/node@2.0.3
  slack: circleci/slack@3.4.2

jobs:
  docker-build-master:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: $DOCKERHUB_USERNAME
          docker-password: $DOCKERHUB_PASS
      - docker/pull:
          images: 'forwardpublishing/ld-varnish-fp-security-update:6.5.2-r1'
      - run:
          name: Build Docker image
          command: |
            TAG=$VERSION_MAJOR.$VERSION_MINOR.$CIRCLE_BUILD_NUM
            echo "Building image with tag: $TAG"
            docker build -t $IMAGE_NAME:$TAG .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            TAG=$VERSION_MAJOR.$VERSION_MINOR.$CIRCLE_BUILD_NUM
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            echo "Pushing image: $IMAGE_NAME:$TAG"
            docker push $IMAGE_NAME:$TAG
      - slack/notify:
          color: '#42e2f4'
          message: Forward publishing varnish is pushed to docker hub
          webhook: ${SLACK_WEBHOOK}

workflows:
  build:
    jobs:
      - docker-build-master:
          filters:
            branches:
              only:
                - master
